function createfigure(X1, Y1, yvector1)
%CREATEFIGURE(X1, Y1, YVECTOR1)
%  X1:  stairs x
%  Y1:  stairs y
%  YVECTOR1:  area yvector

%  Auto-generated by MATLAB on 08-Feb-2018 09:19:24

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create stairs
stairs(X1,Y1,'DisplayName','sinusoīda','Color',[0 0 0]);

% Create area
area(X1,yvector1,'DisplayName','kosinusoīda',...
    'FaceColor',[0.749019622802734 0 0.749019622802734],...
    'LineWidth',1);

% Create xlabel
xlabel('t,s');

% Create title
title('Mans pirmais grafiks');

% Create ylabel
ylabel('U,V');

box(axes1,'on');
grid(axes1,'on');
% Create legend
legend(axes1,'show');